params :
  random_forest_regressor_params:
    max_depth : 6
    max_features : 3
    n_estimators: 100

paths:
  model_pkl_path : "../data/artifacts/random_forest_regressor.pkl"
  data_path : "../data/diabetes_dataset.csv"
  artifacts_path : "../data/artifacts"
  plot_path : "../data/artifacts/plot.png"
  feature_imp_path : "../data/artifacts/feature_importance.csv"